version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"